services:
  - type: web
    name: web
    runtime: node
    region: oregon # optional (defaults to oregon)
    branch: master # optional (defaults to master)
    plan: free # optional (defaults to starter instance type)
    buildCommand: npm install
    startCommand: npm start
    rootDir:
    envVars:
      - key: DB_URL
        fromDatabase:
            name: mysql
            property: connectionString
databases:
  - name: mysql
    plan: free
    databaseName: mydb # optional (Render may add a suffix)
    user: adrian # optional
